import type { ResearchCategory } from './ResearchPlan';

/*
 * Fact — the smallest unit of intelligence inside DEL.
 *
 * Everything downstream operates on Facts instead of raw documents.
 * The Fact Extractor creates these from collected evidence. The Verifier
 * Agent validates them. The Trust Engine scores them. The Conflict Detector
 * flags disagreements. The AI consumes verified facts — never raw webpages.
 *
 * A Fact is a structured statement: subject + predicate + value.
 * Example: "John Smith" + "holds_position" + "CTO at Acme Corp"
 *
 * Each fact preserves full provenance:
 *   - Which sources support it
 *   - Which documents it was extracted from
 *   - When it was extracted
 *   - How it was extracted (manual, heuristic, AI-assisted)
 */

export type VerificationStatus =
  | 'unverified'
  | 'single_source'
  | 'corroborated'
  | 'verified'
  | 'conflicting'
  | 'rejected';

export type FactCategory =
  | 'executive_name'
  | 'current_position'
  | 'company'
  | 'previous_role'
  | 'award'
  | 'interview'
  | 'publication'
  | 'leadership_position'
  | 'company_size'
  | 'company_industry'
  | 'speaking_engagement'
  | 'biography'
  | 'recent_news'
  | ResearchCategory;

export type ExtractionMethod = 'heuristic' | 'ai_assisted' | 'manual' | 'mock';

export interface Fact {
  /** Unique identifier for this fact */
  factId: string;
  /** What category of information this fact represents */
  category: FactCategory;
  /** The entity this fact is about (e.g. "John Smith", "Acme Corp") */
  subject: string;
  /** The relationship/attribute (e.g. "holds_position", "company_industry") */
  predicate: string;
  /** The actual value (e.g. "CTO", "Technology") */
  value: string;
  /** IDs of EvidenceSources that support this fact */
  sourceIds: string[];
  /** Document IDs (from EvidencePackage.documents) this was extracted from */
  extractedFrom: string[];
  /** When this fact was extracted */
  extractedAt: string;
  /** How this fact was extracted */
  extractionMethod: ExtractionMethod;
  /** Confidence score (0-100) — set by the Trust Engine, not the extractor */
  confidence: number;
  /** Verification status — set by the Verifier Agent */
  verificationStatus: VerificationStatus;
  /** Additional metadata */
  metadata: {
    /** IDs of sources that disagree with this fact's value */
    conflictingSourceIds?: string[];
    /** IDs of sources that agree (corroborate) this fact's value */
    corroboratingSourceIds?: string[];
    /** Publication dates of supporting sources (ISO strings) */
    sourceDates?: string[];
    /** Authority scores of supporting sources (0-100) */
    sourceAuthorityScores?: number[];
    /** Whether the fact is considered fresh (published within freshness window) */
    isFresh?: boolean;
    /** Free-text explanation generated by the Trust Engine */
    explanation?: string;
  };
}

export function createFact(partial: Partial<Fact> & Pick<Fact, 'category' | 'subject' | 'predicate' | 'value' | 'sourceIds'>): Fact {
  return {
    factId: partial.factId || `fact-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    category: partial.category,
    subject: partial.subject,
    predicate: partial.predicate,
    value: partial.value,
    sourceIds: partial.sourceIds,
    extractedFrom: partial.extractedFrom || [],
    extractedAt: partial.extractedAt || new Date().toISOString(),
    extractionMethod: partial.extractionMethod || 'heuristic',
    confidence: partial.confidence || 0,
    verificationStatus: partial.verificationStatus || 'unverified',
    metadata: partial.metadata || {},
  };
}
