/*
# Add Intelligence Reports Persistence Table

## Summary
Creates a new `intelligence_reports` table to persist the four ENTERPRISE FROZEN
intelligence reports (MP4–MP7) exactly as generated by their respective coordinators.
Reports are stored as JSONB — structure is never modified, only stored as-is.

Metadata columns are added alongside the JSONB for indexing/queryability:
- report_type (which MP module produced this)
- contact_id (FK to contacts)
- event_id (FK to events, nullable — MP4/MP5 are per-contact, MP6/MP7 are per-contact-per-event)
- overall_confidence (extracted for quick filtering)
- status (generation status)
- generated_at / updated_at (timestamps)

## New Table: `intelligence_reports`
- `id` (uuid, PK)
- `contact_id` (uuid, FK to contacts, NOT NULL)
- `event_id` (uuid, FK to events, nullable — null for per-contact reports)
- `report_type` (text, NOT NULL, CHECK in executive|relationship|strategic_decision|action)
- `report` (jsonb, NOT NULL — the full report object, stored exactly as produced)
- `overall_confidence` (integer, nullable — 0-100 for quick filtering)
- `status` (text, default 'completed', CHECK in completed|stale|partial)
- `generated_at` (timestamptz, default now())
- `updated_at` (timestamptz, default now())
- UNIQUE constraint on (contact_id, event_id, report_type) — one latest report per type per contact/event pair

## Security
- RLS enabled with anon+authenticated CRUD (single-tenant prototype, no auth screen)
- Matches the existing pattern used by all other DEL tables

## Important Notes
1. Reports are stored exactly as produced — no structural mutations
2. The UNIQUE constraint means re-running the pipeline upserts (replaces) the latest report
3. `event_id` is nullable because MP4 (Executive Intelligence) and MP5 (Relationship Intelligence)
   are per-contact only; MP6 (Strategic Decision) and MP7 (Action Intelligence) are per-contact-per-event
4. `overall_confidence` is stored as metadata for indexing — it does not modify the report JSONB
*/

CREATE TABLE IF NOT EXISTS intelligence_reports (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  contact_id uuid NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  event_id uuid REFERENCES events(id) ON DELETE CASCADE,
  report_type text NOT NULL CHECK (report_type IN ('executive', 'relationship', 'strategic_decision', 'action')),
  report jsonb NOT NULL,
  overall_confidence integer,
  status text NOT NULL DEFAULT 'completed' CHECK (status IN ('completed', 'stale', 'partial')),
  generated_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(contact_id, event_id, report_type)
);

ALTER TABLE intelligence_reports ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_intel_reports" ON intelligence_reports;
CREATE POLICY "anon_select_intel_reports" ON intelligence_reports FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_intel_reports" ON intelligence_reports;
CREATE POLICY "anon_insert_intel_reports" ON intelligence_reports FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_intel_reports" ON intelligence_reports;
CREATE POLICY "anon_update_intel_reports" ON intelligence_reports FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_intel_reports" ON intelligence_reports;
CREATE POLICY "anon_delete_intel_reports" ON intelligence_reports FOR DELETE
  TO anon, authenticated USING (true);

CREATE INDEX IF NOT EXISTS idx_intel_reports_contact_id ON intelligence_reports(contact_id);
CREATE INDEX IF NOT EXISTS idx_intel_reports_event_id ON intelligence_reports(event_id);
CREATE INDEX IF NOT EXISTS idx_intel_reports_type ON intelligence_reports(report_type);
CREATE INDEX IF NOT EXISTS idx_intel_reports_confidence ON intelligence_reports(overall_confidence DESC);